triggers:
- repos:
  - multicloudlab
  trusted_org: multicloudlab
  elide_skipped_contexts: true

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins

plugins:
  multicloudlab:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - slackevents
  - trigger
  - verify-owners
  - wip

  multicloudlab/test-infra:
  - config-updater

external_plugins:
  multicloudlab:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
      - issue_comment
      - pull_request
