# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - multicloudlab
  trusted_org: multicloudlab
  elide_skipped_contexts: true

plugins:
  multicloudlab/oasis:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - size
  - slackevents
  - trigger
  - verify-owners
  - wip

external_plugins:
  multicloudlab:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
      - issue_comment
      - pull_request
